---
version: "2"

services:
  wordpress:
    image: "wordpress:latest"
    links: 
      - wp_db
    depends_on:
      - wp_db
    ports: 
      - 8080:80
    environment:
      - "WORDPRESS_DB_HOST=wp_db"
      - "WORDPRESS_DB_USER=root"
      - "WORDPRESS_DB_PASSWORD=Ohz6Ii4ingeb"
      - "WORDPRESS_DB_NAME=wb_db"

  wp_db:
    image: "mysql:latest"
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      - "MYSQL_ROOT_PASSWORD=Ohz6Ii4ingeb"
    
